version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: studia-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: studia_db
      MYSQL_USER: studia_user
      MYSQL_PASSWORD: ${DB_PASSWORD:-studia_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - studia-network

  backend:
    build: ./Backend
    container_name: studia-backend
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: studia_db
      DB_USERNAME: studia_user
      DB_PASSWORD: ${DB_PASSWORD:-studia_password}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - upload_files:/app/uploads
      - app_logs:/var/log/studia
    networks:
      - studia-network

  frontend:
    image: nginx:alpine
    container_name: studia-frontend
    ports:
      - "80:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - studia-network

volumes:
  mysql_data:
  upload_files:
  app_logs:

networks:
  studia-network:
    driver: bridge
