spring:
  application:
    name: studia-backend
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:mysql}  # 기본값은 mysql
    
  datasource:
    url: jdbc:mysql://localhost:3306/studia_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:studia_user}
    password: ${DB_PASSWORD:studia_password} 
    
  h2:
    console:
      enabled: false
      path: /h2-console
    
  jpa:
    hibernate:
      ddl-auto: update  # 프로덕션에서는 validate 사용 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    
  servlet:
    multipart:
      max-file-size: 100MB  # 대용량 파일 지원
      max-request-size: 100MB
      
  redis:
    host: localhost
    port: 6379
    enabled: false  # Redis 비활성화 명시
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              
server:
  port: 8080
  
jwt:
  secret: ${JWT_SECRET:S3l2UGx0VmJGRlJ5eWZVSkd0dHBMa3hKUmVaZW5kZXVwZ3dkV1JXb3FBU2RLRW5aQ3JZR29CTDJnSVk4Y1ZTSkVOVXpHNA==}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days
  
openai:
  api:
    key: ${OPENAI_API_KEY:test-key}
    url: https://api.openai.com/v1/chat/completions
    
claude:
  api:
    key: ${CLAUDE_API_KEY:test-key}
    url: https://api.anthropic.com/v1/messages
    
ai:
  model: ${AI_MODEL:openai}  # openai or claude
    
file:
  upload:
    path: ${FILE_UPLOAD_PATH:./uploads}
    
logging:
  level:
    Study.Assistant.Studia: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
